//
//  WorkbookBank.swift
//  SwiftMandarin
//
//  Persistence for the Photo-tab workbook features:
//  - `WorkbookQuestion`: one reviewable question (saved from a graded workbook
//    or generated by the AI as fresh practice).
//  - `WorkbookQuestionBankStore`: the user's review-question database.
//  - `GradedSession` + `WorkbookGradingHistoryStore`: a history of past graded
//    workbooks, each keeping its original scanned photos.
//  - `WorkbookImageStore`: a small file-backed image store. The scanned photos
//    are far too large for the UserDefaults-backed JSON stores, so their bytes
//    live on disk under Application Support and the JSON only keeps file IDs.
//
//  All Codable types decode tolerantly (every field falls back to a default) so
//  adding fields later never throws on older payloads — mirroring the rest of
//  the app's stores (see PersistentCodableStore).
//

import Foundation
import SwiftUI
import Observation
import os.log

// MARK: - Workbook Question

/// A single question the learner can review later: either lifted from a graded
/// workbook (`isGenerated == false`) or produced by the AI as new practice
/// (`isGenerated == true`).
struct WorkbookQuestion: Identifiable, Codable, Equatable, Hashable {
    let id: UUID
    var questionNumber: String
    var question: String
    var studentAnswer: String
    var correctAnswer: String
    var wasCorrect: Bool
    var explanation: String
    /// Complete sentence in the learning language for read-aloud practice.
    var fullSentence: String
    var vocabTerm: String
    var vocabReading: String
    var vocabMeaning: String
    /// Optional free-text grouping (e.g. "Unit 3", "动词时态"); "" = ungrouped.
    var subject: String
    var dateAdded: Date
    var timesReviewed: Int
    /// True when the AI generated this as fresh practice (no student answer).
    var isGenerated: Bool

    init(
        id: UUID = UUID(),
        questionNumber: String = "",
        question: String,
        studentAnswer: String = "",
        correctAnswer: String,
        wasCorrect: Bool = false,
        explanation: String = "",
        fullSentence: String = "",
        vocabTerm: String = "",
        vocabReading: String = "",
        vocabMeaning: String = "",
        subject: String = "",
        dateAdded: Date = Date(),
        timesReviewed: Int = 0,
        isGenerated: Bool = false
    ) {
        self.id = id
        self.questionNumber = questionNumber
        self.question = question
        self.studentAnswer = studentAnswer
        self.correctAnswer = correctAnswer
        self.wasCorrect = wasCorrect
        self.explanation = explanation
        self.fullSentence = fullSentence
        self.vocabTerm = vocabTerm
        self.vocabReading = vocabReading
        self.vocabMeaning = vocabMeaning
        self.subject = subject
        self.dateAdded = dateAdded
        self.timesReviewed = timesReviewed
        self.isGenerated = isGenerated
    }

    enum CodingKeys: String, CodingKey {
        case id, questionNumber, question, studentAnswer, correctAnswer, wasCorrect
        case explanation, fullSentence, vocabTerm, vocabReading, vocabMeaning
        case subject, dateAdded, timesReviewed, isGenerated
    }

    // Tolerant decode so newly-added fields never break older saved data.
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = (try? c.decode(UUID.self, forKey: .id)) ?? UUID()
        questionNumber = (try? c.decode(String.self, forKey: .questionNumber)) ?? ""
        question = (try? c.decode(String.self, forKey: .question)) ?? ""
        studentAnswer = (try? c.decode(String.self, forKey: .studentAnswer)) ?? ""
        correctAnswer = (try? c.decode(String.self, forKey: .correctAnswer)) ?? ""
        wasCorrect = (try? c.decode(Bool.self, forKey: .wasCorrect)) ?? false
        explanation = (try? c.decode(String.self, forKey: .explanation)) ?? ""
        fullSentence = (try? c.decode(String.self, forKey: .fullSentence)) ?? ""
        vocabTerm = (try? c.decode(String.self, forKey: .vocabTerm)) ?? ""
        vocabReading = (try? c.decode(String.self, forKey: .vocabReading)) ?? ""
        vocabMeaning = (try? c.decode(String.self, forKey: .vocabMeaning)) ?? ""
        subject = (try? c.decode(String.self, forKey: .subject)) ?? ""
        dateAdded = (try? c.decode(Date.self, forKey: .dateAdded)) ?? Date()
        timesReviewed = (try? c.decode(Int.self, forKey: .timesReviewed)) ?? 0
        isGenerated = (try? c.decode(Bool.self, forKey: .isGenerated)) ?? false
    }

    /// True when this question carries a usable study-vocab item.
    var hasVocab: Bool {
        !vocabTerm.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    /// Text to read aloud (in the learning language): the full sentence if
    /// present, otherwise the correct answer, otherwise the question.
    var spokenSentence: String {
        let sentence = fullSentence.trimmingCharacters(in: .whitespacesAndNewlines)
        if !sentence.isEmpty { return sentence }
        let answer = correctAnswer.trimmingCharacters(in: .whitespacesAndNewlines)
        if !answer.isEmpty { return answer }
        return question
    }
}

extension WorkbookQuestion {
    /// Build a bank question from a freshly graded question.
    init(graded q: GradedQuestion, subject: String = "") {
        self.init(
            questionNumber: q.questionNumber,
            question: q.question,
            studentAnswer: q.studentAnswer,
            correctAnswer: q.correctAnswer,
            wasCorrect: q.isCorrect,
            explanation: q.explanation,
            fullSentence: q.fullSentence,
            vocabTerm: q.vocab?.term ?? "",
            vocabReading: q.vocab?.reading ?? "",
            vocabMeaning: q.vocab?.meaning ?? "",
            subject: subject,
            isGenerated: false
        )
    }

    /// Build a bank question from an AI-generated review question.
    init(generated g: GeneratedReviewQuestion, subject: String = "") {
        self.init(
            question: g.prompt,
            correctAnswer: g.answer,
            wasCorrect: false,
            explanation: g.explanation,
            fullSentence: g.fullSentence,
            subject: subject,
            isGenerated: true
        )
    }
}

// MARK: - Question Bank Store

/// The learner's review-question database. Newest questions first.
@Observable
@MainActor
final class WorkbookQuestionBankStore {
    static let shared = WorkbookQuestionBankStore()

    private(set) var questions: [WorkbookQuestion] = []

    private let saveKey = "workbookQuestionBank"

    private init() { load() }

    var count: Int { questions.count }

    /// Distinct non-empty subjects, alphabetically.
    var subjects: [String] {
        Array(Set(questions.map(\.subject).filter { !$0.isEmpty })).sorted()
    }

    /// Add a question unless an equivalent one (same prompt + answer) exists.
    /// Returns true when the question was newly added.
    @discardableResult
    func add(_ question: WorkbookQuestion) -> Bool {
        let key = Self.dedupKey(question)
        guard !key.isEmpty else { return false }
        guard !questions.contains(where: { Self.dedupKey($0) == key }) else { return false }
        questions.insert(question, at: 0)
        save()
        return true
    }

    func contains(_ question: WorkbookQuestion) -> Bool {
        let key = Self.dedupKey(question)
        return !key.isEmpty && questions.contains { Self.dedupKey($0) == key }
    }

    func containsGraded(_ graded: GradedQuestion) -> Bool {
        contains(WorkbookQuestion(graded: graded))
    }

    func remove(_ question: WorkbookQuestion) {
        questions.removeAll { $0.id == question.id }
        save()
    }

    func remove(at offsets: IndexSet) {
        questions.remove(atOffsets: offsets)
        save()
    }

    func clear() {
        questions.removeAll()
        save()
    }

    func markReviewed(_ question: WorkbookQuestion) {
        guard let index = questions.firstIndex(where: { $0.id == question.id }) else { return }
        questions[index].timesReviewed += 1
        save()
    }

    /// Questions matching a subject filter (nil/"" = all).
    func questions(in subject: String?) -> [WorkbookQuestion] {
        guard let subject, !subject.isEmpty else { return questions }
        return questions.filter { $0.subject == subject }
    }

    private static func dedupKey(_ q: WorkbookQuestion) -> String {
        (q.question + "∣" + q.correctAnswer)
            .lowercased()
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private func load() {
        if let decoded = PersistentCodableStore.load([WorkbookQuestion].self, key: saveKey) {
            questions = decoded
        }
    }

    private func save() {
        PersistentCodableStore.save(questions, key: saveKey)
    }
}

// MARK: - Graded Session (history)

/// A past graded workbook kept for review, including references to the original
/// scanned photos (stored on disk via `WorkbookImageStore`).
struct GradedSession: Identifiable, Codable {
    let id: UUID
    var date: Date
    var score: String
    var summary: String
    var questions: [WorkbookQuestion]
    var workbookImageIDs: [String]
    var answerImageIDs: [String]
    var customInstructions: String

    init(
        id: UUID = UUID(),
        date: Date = Date(),
        score: String = "",
        summary: String = "",
        questions: [WorkbookQuestion] = [],
        workbookImageIDs: [String] = [],
        answerImageIDs: [String] = [],
        customInstructions: String = ""
    ) {
        self.id = id
        self.date = date
        self.score = score
        self.summary = summary
        self.questions = questions
        self.workbookImageIDs = workbookImageIDs
        self.answerImageIDs = answerImageIDs
        self.customInstructions = customInstructions
    }

    enum CodingKeys: String, CodingKey {
        case id, date, score, summary, questions, workbookImageIDs, answerImageIDs, customInstructions
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id = (try? c.decode(UUID.self, forKey: .id)) ?? UUID()
        date = (try? c.decode(Date.self, forKey: .date)) ?? Date()
        score = (try? c.decode(String.self, forKey: .score)) ?? ""
        summary = (try? c.decode(String.self, forKey: .summary)) ?? ""
        questions = (try? c.decode([WorkbookQuestion].self, forKey: .questions)) ?? []
        workbookImageIDs = (try? c.decode([String].self, forKey: .workbookImageIDs)) ?? []
        answerImageIDs = (try? c.decode([String].self, forKey: .answerImageIDs)) ?? []
        customInstructions = (try? c.decode(String.self, forKey: .customInstructions)) ?? ""
    }

    var correctCount: Int { questions.filter { $0.wasCorrect }.count }
    var totalCount: Int { questions.count }
    var allImageIDs: [String] { workbookImageIDs + answerImageIDs }
    var displayScore: String { score.isEmpty ? "\(correctCount)/\(totalCount)" : score }
}

// MARK: - Grading History Store

/// History of graded workbooks. Newest first. Deleting a session also deletes
/// its scanned photos from disk so the image store never leaks orphans.
@Observable
@MainActor
final class WorkbookGradingHistoryStore {
    static let shared = WorkbookGradingHistoryStore()

    private(set) var sessions: [GradedSession] = []

    private let saveKey = "workbookGradingHistory"

    private init() { load() }

    var count: Int { sessions.count }

    func add(_ session: GradedSession) {
        sessions.insert(session, at: 0)
        save()
    }

    func remove(_ session: GradedSession) {
        WorkbookImageStore.deleteAll(session.allImageIDs)
        sessions.removeAll { $0.id == session.id }
        save()
    }

    func remove(at offsets: IndexSet) {
        for index in offsets where sessions.indices.contains(index) {
            WorkbookImageStore.deleteAll(sessions[index].allImageIDs)
        }
        sessions.remove(atOffsets: offsets)
        save()
    }

    func clear() {
        for session in sessions {
            WorkbookImageStore.deleteAll(session.allImageIDs)
        }
        sessions.removeAll()
        save()
    }

    private func load() {
        if let decoded = PersistentCodableStore.load([GradedSession].self, key: saveKey) {
            sessions = decoded
        }
    }

    private func save() {
        PersistentCodableStore.save(sessions, key: saveKey)
    }
}

// MARK: - Image Store (file-backed)

/// Stores scanned workbook photos as files under Application Support, keyed by
/// a generated ID. Kept out of UserDefaults because image payloads are large.
/// All methods are nonisolated (pure file IO) — call the heavy ones off the
/// main actor (e.g. inside a detached task) to avoid blocking the UI.
enum WorkbookImageStore {

    // `nonisolated` throughout: the project defaults to MainActor isolation, but
    // this is pure file IO with no shared mutable state, so it must be callable
    // off the main actor (e.g. from the detached tasks that save/load scans)
    // without blocking the UI.
    nonisolated private static let log = Logger(subsystem: "com.rogerlin.SwiftMandarin", category: "WorkbookImageStore")

    nonisolated private static var directory: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.temporaryDirectory
        let dir = base.appendingPathComponent("WorkbookImages", isDirectory: true)
        if !FileManager.default.fileExists(atPath: dir.path) {
            do {
                try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            } catch {
                log.error("Failed to create image directory: \(error.localizedDescription, privacy: .public)")
            }
        }
        return dir
    }

    nonisolated private static func url(for id: String) -> URL {
        directory.appendingPathComponent(id + ".jpg")
    }

    /// Persist image bytes; returns the generated ID, or nil on failure.
    nonisolated static func save(_ data: Data) -> String? {
        let id = UUID().uuidString
        do {
            try data.write(to: url(for: id), options: .atomic)
            return id
        } catch {
            log.error("Failed to save image: \(error.localizedDescription, privacy: .public)")
            return nil
        }
    }

    /// Persist several images, returning the IDs that saved successfully.
    nonisolated static func saveAll(_ datas: [Data]) -> [String] {
        datas.compactMap { save($0) }
    }

    nonisolated static func load(_ id: String) -> Data? {
        try? Data(contentsOf: url(for: id))
    }

    nonisolated static func delete(_ id: String) {
        try? FileManager.default.removeItem(at: url(for: id))
    }

    nonisolated static func deleteAll(_ ids: [String]) {
        ids.forEach(delete)
    }
}
